In [1]:
# Corpus to be used for this assignment

corpus = [
     'this is the first document mostly',
     'this document is the second document',
     'and this is the third one',
     'is this the first document here',
]

doc1 = "this is the first document mostly"
doc2 = "this document is the second document"
doc3 = "and this is the third one"
doc4 = "is this the first document here"

BOW1 = doc1.split(" ")
BOW2 = doc2.split(" ")
BOW3 = doc3.split(" ")
BOW4 = doc4.split(" ")

set_of_words = set(BOW1).union(set(BOW2)).union(set(BOW3)).union(set(BOW4))
print(set_of_words)

wdict1 = dict.fromkeys(set_of_words,0)
wdict2 = dict.fromkeys(set_of_words,0)
wdict3 = dict.fromkeys(set_of_words,0)
wdict4 = dict.fromkeys(set_of_words,0)

for word in BOW1:
    wdict1[word] += 1
for word in BOW2:
    wdict2[word] += 1
for word in BOW3:
    wdict3[word] += 1
for word in BOW4:
    wdict4[word] += 1

#print(wdict1)
#print(wdict2)
#print(wdict3)
#print(wdict4)


{'and', 'the', 'here', 'one', 'first', 'this', 'third', 'is', 'mostly', 'document', 'second'}


In [2]:
#Computing TF values
#counting the number of sentences of words in Set of words
tfdict = dict.fromkeys(set_of_words,0)

for word in set_of_words:
  count = 0
  for doc in corpus:
    if word in doc:
      count += 1
  tfdict[word] = count

print(tfdict)

{'and': 1, 'the': 4, 'here': 1, 'one': 1, 'first': 2, 'this': 4, 'third': 1, 'is': 4, 'mostly': 1, 'document': 3, 'second': 1}


In [3]:
#Computing IDF values
import numpy as np
import math
idfdict = dict.fromkeys(set_of_words,0)

for word,count in tfdict.items():
    idfdict[word] = np.log((4)/(count))
idfdict

print(idfdict)



{'and': 1.3862943611198906, 'the': 0.0, 'here': 1.3862943611198906, 'one': 1.3862943611198906, 'first': 0.6931471805599453, 'this': 0.0, 'third': 1.3862943611198906, 'is': 0.0, 'mostly': 1.3862943611198906, 'document': 0.28768207245178085, 'second': 1.3862943611198906}


In [28]:
# Please implement this fucntion and write your code wherever asked. Do NOT change the code snippets provided by us.
from collections import Counter
def computeTFIDF (corpus):
  ##############################################################
  ####   YOUR CODE BELOW  as per the above instructions #######
  ##############################################################
  #computing TFIDF values

  TFIDF = []
  for doc in corpus:
    doc = list(doc.split())
    rep_of_words = Counter(doc)
    tfidf_doc = []
    for word in doc:
      #assinging the idfdict values to IDF
      IDF = idfdict[word]
      #computing the TF values for the iterating words
      TF = rep_of_words[word]/len(doc)
      #calculating the tfidf values and rounding it to 2 decimal places
      tfidf_words = (TF * IDF)
      tfidf_doc.append(round((tfidf_words),2))
    TFIDF.append(tfidf_doc)
  TFIDF = np.array(TFIDF)
  #printing TFIDF values
  print(TFIDF)
  return TFIDF
tfidfs = computeTFIDF(corpus)



  

[[0.   0.   0.   0.12 0.05 0.23]
 [0.   0.1  0.   0.   0.23 0.1 ]
 [0.23 0.   0.   0.   0.23 0.23]
 [0.   0.   0.   0.12 0.05 0.23]]


In [29]:
computeTFIDF(corpus)

[[0.   0.   0.   0.12 0.05 0.23]
 [0.   0.1  0.   0.   0.23 0.1 ]
 [0.23 0.   0.   0.   0.23 0.23]
 [0.   0.   0.   0.12 0.05 0.23]]


array([[0.  , 0.  , 0.  , 0.12, 0.05, 0.23],
       [0.  , 0.1 , 0.  , 0.  , 0.23, 0.1 ],
       [0.23, 0.  , 0.  , 0.  , 0.23, 0.23],
       [0.  , 0.  , 0.  , 0.12, 0.05, 0.23]])

In [30]:
###########################################
## GRADER CELL: Do NOT Change this.
# This cell will print "Success" if your implmentation of the computeTFIDF() is correct.
# Else, it will print "Failed"
###########################################
import numpy as np

# compute TF-IDF using the computeTFIDF() function
X_custom = computeTFIDF(corpus)

# Reference grader array - DO NOT MODIFY IT
X_grader = np.array(
    [[0, 0, 0, 0.12, 0.05, 0.23],
     [0, 0.1, 0, 0, 0.23, 0.1],
     [0.23, 0, 0, 0, 0.23, 0.23],
     [0, 0, 0, 0.12, 0.05, 0.23]]
     )

# compare X_grader and X_custom
comparison = ( X_grader == X_custom )
isEqual = comparison.all()

if isEqual:
  print("******** Success ********")
else:
  print("####### Failed #######")
  print("\nX_grader = \n\n", X_grader)
  print("\n","*"*50)
  print("\nX_custom = \n\n", X_custom)


[[0.   0.   0.   0.12 0.05 0.23]
 [0.   0.1  0.   0.   0.23 0.1 ]
 [0.23 0.   0.   0.   0.23 0.23]
 [0.   0.   0.   0.12 0.05 0.23]]
******** Success ********
